api_url: https://api.binance.com
api_key: "YOUR_API_KEY"
api_secret: "YOUR_API_SECRET"
database_path: binance_1m.db
symbols: [BTCUSDT, ETHUSDT]
interval: '1m'
mode: live   # live | test | backtest
log_level: INFO
log_file: bot.log
watchdog_timeout: 120
cycle_sleep: 60
download_retries: 3
request_timeout: 10
population_path: population.json
population_size: 4
mutation_rate: 0.1
selection_pct: 0.5
trade_size: 10
balance: 1000
