api_url: https://api.binance.com
# Path to the SQLite database used by bot.py and train_model.py
database_path: binance_1m.db
# Explicit symbols to download. Leave empty to fetch top 30
symbols: []
# How many days of historical data to download
history_days: 7
# Kline interval
interval: '1m'
# Log level for console and file handlers (e.g. INFO, DEBUG, WARNING)
log_level: INFO
# Path to the log file
log_file: bot.log
# Retry configuration for Binance API requests
# How many times to retry a failed request
retry_attempts: 3
# Base delay in seconds between retries (exponential backoff)
retry_backoff: 1.0
# API credentials for live trading
api_key: ""
api_secret: ""
